#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: Update Checker

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  FEED_REPO_URL: https://github.com/fw876/helloworld
  REPO_BRANCH: master

on:
  workflow_dispatch:
  schedule:
    - cron: 0 22 * * *

jobs:
  check:
    runs-on: ubuntu-20.04

    steps:

    - name: Get Commit Hash
      id: getHash
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        git clone --depth 1 $FEED_REPO_URL feed
        cd openwrt
        echo "::set-output name=commitHash::$(git rev-parse HEAD)"
        cd ../feed
        echo "::set-output name=feedcommitHash::$(git rev-parse HEAD)"

    - name: Compare Commit Hash
      id: cacheHash
      uses: actions/cache@v2
      with:
        path: .commitHash
        key: HEAD-${{ steps.getHash.outputs.commitHash }}

    - name: Compare Feed Commit Hash
      id: feedcacheHash
      uses: actions/cache@v2
      with:
        path: .feedcommitHash
        key: HEAD-${{ steps.getHash.outputs.feedcommitHash }}

    - name: Save New Commit Hash
      if: steps.cacheHash.outputs.cache-hit != 'true' || steps.feedcacheHash.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash
        echo ${{ steps.getHash.outputs.feedcommitHash }} | tee .feedcommitHash

    - name: Trigger build
      if: steps.cacheHash.outputs.cache-hit != 'true' || steps.feedcacheHash.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_REPO_PAT }}
        event-type: Source Code Update

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
